name: Increment Number

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  increment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full commit history is available

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Pull Latest Changes
        run: |
          git pull --rebase origin main  # Ensure the local branch is up-to-date

      - name: Increment Number
        run: |
          if [ ! -f number.txt ]; then
            echo "0" > number.txt
          fi
          number=$(cat number.txt)
          echo $((number + 1)) > number.txt
          echo "Updated number.txt to $(cat number.txt)"

      - name: Commit and Push Changes
        run: |
          git add number.txt
          git commit -m "Increment number to $(cat number.txt)" || echo "No changes to commit"
          git push origin main
