name: Increment Number

on:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  increment-number:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Read and Increment Number
        run: |
          # Ensure the file exists
          if [ ! -f number.txt ]; then
            echo "0" > number.txt
          fi

          # Read the number, increment it, and save it back
          number=$(cat number.txt)
          new_number=$((number + 1))
          echo $new_number > number.txt
          echo "Incremented number to: $new_number"

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git add number.txt
          git commit -m "Increment number to $(cat number.txt)"
          git push
