name: Run Main Script

on:
  workflow_dispatch:  # Allows manual triggering from GitHub UI
  push:
    branches:
      - main          # Runs when code is pushed to the 'main' branch
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full history is available

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Use the latest Python 3 version

      - name: Install Dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found, skipping installation."
          fi

      - name: Run Main Script
        run: python main.py
